spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/task_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect


jwt-tokens:
  access:
    expiration-hours: 24
  refresh:
    expiration-hours: 72
