spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/task_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  ai:
    openai:
      api-key: ${OPEN_API_KEY}
      chat:
        options:
          model: gpt-4

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt-tokens:
  access:
    expiration-hours: 24
  refresh:
    expiration-hours: 72

minio:
  url: ${MINIO_URL:http://localhost:9000}
  access-key: ${MINIO_USER:minioadmin}
  secret-key: ${MINIO_PASSWORD:minioadmin}
  bucket: task-manager
